SpotifySuggestions/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SpotifySuggestions.Models.Configurations;

namespace SpotifySuggestions.Controllers
{
	[Route("api")]
	[ApiController]
	public class AuthenticationController : Controller
	{
		private readonly SpotifyConfiguration _spotifyConfiguration;

		public AuthenticationController(SpotifyConfiguration spotifyConfiguration)
		{
			_spotifyConfiguration = spotifyConfiguration;
		}
		
		[HttpGet("login")]
		public IActionResult Login()
		{
			var scopes =
				HttpUtility.UrlEncode(
					_spotifyConfiguration.Scopes.Aggregate(string.Empty, (current, scope) => current + $"{scope} "));

			return Redirect("https://accounts.spotify.com/authorize?" +
			                $"client_id={_spotifyConfiguration.ClientId}&" +
			                "response_type=code&" +
			                $"redirect_uri={Environment.GetEnvironmentVariable("baseUrl")}/api/callback&" +
			                $"scope={scopes}&prompt=consent");
		}
		
		[HttpGet("callback")]
		public async Task<IActionResult> CallbackAsync(string code, string error)
		{
			if (error == null)
			{
				var httpClient = new HttpClient();
				var request = new HttpRequestMessage
				{
					RequestUri = new Uri("https://accounts.spotify.com/api/token"),
					Method = HttpMethod.Post,
					Content = new FormUrlEncodedContent(new[]
					{
						new KeyValuePair<string, string>("grant_type", "authorization_code"),
						new KeyValuePair<string, string>("code", code),
						new KeyValuePair<string, string>("redirect_uri",
							Environment.GetEnvironmentVariable("baseUrl") + "/api/callback"),
						new KeyValuePair<string, string>("client_id", _spotifyConfiguration.ClientId),
						new KeyValuePair<string, string>("client_secret", _spotifyConfiguration.ClientSecret)
					})
				};

				var response = await httpClient.SendAsync(request);
				var responseObject = JsonConvert.DeserializeObject<JObject>(await response.Content.ReadAsStringAsync());
				var accessToken = responseObject.SelectToken("access_token");
				var refreshToken = responseObject.SelectToken("refresh_token");

				if (accessToken != null && refreshToken != null)
				{
					HttpContext.Session.SetString("access_token", accessToken.ToString());
					HttpContext.Session.SetString("refresh_token", refreshToken.ToString());
				}

				return Redirect("/");
			}

			return Redirect("/");
		}
		
		[HttpGet("logout")]
		public IActionResult Logout()
		{
			HttpContext.Session.Clear();

			return Redirect("/");
		}
	}
}

SpotifySuggestions/Pages/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SpotifyAPI.Web;
using SpotifySuggestions.Models.Configurations;

namespace SpotifySuggestions.Pages
{
	public class IndexModel : PageModel
	{
		private readonly SpotifyConfiguration _spotifyConfiguration;
		private readonly BugsnagConfiguration _bugsnagConfiguration;
		
		public IndexModel(SpotifyConfiguration spotifyConfiguration, BugsnagConfiguration bugsnagConfiguration)
		{
			_spotifyConfiguration = spotifyConfiguration;
			_bugsnagConfiguration = bugsnagConfiguration;
		}
		
		public async Task OnGet()
		{
			var accessToken = HttpContext.Session.GetString("access_token");

			if (accessToken == null) return;

			ViewData["bugsnag-apikey"] = _bugsnagConfiguration.ClientApiKey;
			ViewData["app-version"] = GetType().Assembly.GetName().Version?.ToString();
			
			try
			{
				var spotifyClient = new SpotifyClient(accessToken);
				var user = await spotifyClient.UserProfile.Current();

				ViewData["username"] = user.DisplayName;
			}
			catch (APIUnauthorizedException)
			{
				var refreshToken = HttpContext.Session.GetString("refresh_token");

				var response = await new OAuthClient().RequestToken(
					new AuthorizationCodeRefreshRequest(_spotifyConfiguration.ClientId,
						_spotifyConfiguration.ClientSecret, refreshToken));
				
				HttpContext.Session.SetString("access_token", response.AccessToken);
				
				var spotifyClient = new SpotifyClient(response.AccessToken);
				var user = await spotifyClient.UserProfile.Current();

				ViewData["username"] = user.DisplayName;
			}
		}
	}
}

SpotifySuggestions/Pages/Index.cshtml
@page
@model IndexModel

<div id="layoutDefault">
    <div id="layoutDefault_content">
        <main>
            <header class="page-header page-header-dark bg-success">
                <div class="page-header-content">
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-xl-8 col-lg-10 text-center">
                                <h1 id="top" class="page-header-title" data-aos="fade-up">music you'll (probably) like</h1>
                                <p class="page-header-text mb-3" data-aos="fade-up">A site to help you find new music based on what you currently listen to.</p>
                                @if (ViewData["username"] != null)
                                {
                                    <button class="btn btn-black btn-block mb-3 btn-marketing rounded-pill" data-aos="zoom-in" data-aos-delay="250">Logged in as @ViewData["username"]</button>
                                    <p class="page-header-text small mb-0" data-aos="fade-up">Not the right account? You can <a asp-controller="Authentication" asp-action="Logout">log out</a> here.</p>
                                }
                                else
                                {
                                    <a class="btn btn-black btn-block mb-3 btn-marketing rounded-pill text-lg btn-lg" data-aos="zoom-in" data-aos-delay="250" asp-controller="Authentication" asp-action="Login"><i class="fab fa-spotify"></i> Sign in with Spotify</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <div class="svg-border-waves text-white">
                    <svg class="wave" style="pointer-events: none" fill="currentColor" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1920 75">
                        <defs>
                            <style>
                                        .a {
                                            fill: none;
                                        }
                                        .b {
                                            clip-path: url(#a);
                                        }
                                        .d {
                                            opacity: 0.5;
                                            isolation: isolate;
                                        }
                                    </style>
                            <clippath id="a">
                                <rect class="a" width="1920" height="75"></rect>
                            </clippath>
                        </defs>
                        <title>wave</title>
                        <g class="b">
                            <path class="c" d="M1963,327H-105V65A2647.49,2647.49,0,0,1,431,19c217.7,3.5,239.6,30.8,470,36,297.3,6.7,367.5-36.2,642-28a2511.41,2511.41,0,0,1,420,48"></path>
                        </g>
                        <g class="b">
                            <path class="d" d="M-127,404H1963V44c-140.1-28-343.3-46.7-566,22-75.5,23.3-118.5,45.9-162,64-48.6,20.2-404.7,128-784,0C355.2,97.7,341.6,78.3,235,50,86.6,10.6-41.8,6.9-127,10"></path>
                        </g>
                        <g class="b">
                            <path class="d" d="M1979,462-155,446V106C251.8,20.2,576.6,15.9,805,30c167.4,10.3,322.3,32.9,680,56,207,13.4,378,20.3,494,24"></path>
                        </g>
                        <g class="b">
                            <path class="d" d="M1998,484H-243V100c445.8,26.8,794.2-4.1,1035-39,141-20.4,231.1-40.1,378-45,349.6-11.6,636.7,73.8,828,150"></path>
                        </g>
                    </svg>
                </div>
            </header>
            <section class="bg-white pt-5 pb-10">
                <div class="container text-center">
                    @if (ViewData["username"] == null)
                    {
                        <h4 class="mb-5">Get suggestions for new music based on a variety of options:</h4>
                        <div class="row text-center">
                            <div class="col-lg-4 mb-5 mb-lg-0">
                                <div class="icon-stack icon-stack-xl bg-green text-white mb-4">
                                    <i data-feather="headphones"></i>
                                </div>
                                <p class="mb-0">A playlist. Paste in the URL of a public Spotify playlist, or one you own, to find new music of a similar style.</p>
                            </div>
                            <div class="col-lg-4 mb-5 mb-lg-0">
                                <div class="icon-stack icon-stack-xl bg-green text-white mb-4">
                                    <i data-feather="music"></i>
                                </div>
                                <p class="mb-0">Your previous listening activity. This can either be over a long period (many years), medium (6 months) or short term (4 weeks).</p>
                            </div>
                            <div class="col-lg-4">
                                <div class="icon-stack icon-stack-xl bg-green text-white mb-4">
                                    <i data-feather="volume-2"></i>
                                </div>
                                <p class="mb-0">A custom selection. Select up to 5 artists or songs to find other content you'll enjoy.</p>
                            </div>
                        </div>
                        <h5 class="mt-5">Ready to find new music? Click the button above to login using Spotify.</h5>
                        <a class="mb-5 text-green" href="#top">Take me to the top!</a>
                    }
                    else
                    {
                        <div id="pre-search">
                            <h4>Use the dropdown below to select how you want to find new music:</h4>
                            <select id="first-select" class="form-control my-3">
                                <option selected disabled>Select...</option>
                                <option value="top">Listening Activity</option>
                                <option value="public-playlist">Playlist URL</option>
                                <option value="private-playlist">Private Playlist</option>
                                <option value="custom">Custom Selection</option>
                            </select>
                            <div id="second-step"></div>
                            <div class="text-red mb-3 font-weight-700" id="music-error" hidden></div>
                            <button class="btn btn-green w-100" id="music-button">Find me music!</button>
                        </div>
                        <div id="post-search" hidden></div>
                    }
                </div>
                <div class="svg-border-waves text-black">
                    <svg class="wave" style="pointer-events: none" fill="currentColor" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 1920 75">
                        <defs>
                            <style>
                                        .a {
                                            fill: none;
                                        }
                                        .b {
                                            clip-path: url(#e);
                                        }
                                        .d {
                                            opacity: 0.5;
                                            isolation: isolate;
                                        }
                                    </style>
                            <clippath id="e">
                                <rect class="a" width="1920" height="75"></rect>
                            </clippath>
                        </defs>
                        <title>wave</title>
                        <g class="b">
                            <path class="c" d="M1963,327H-105V65A2647.49,2647.49,0,0,1,431,19c217.7,3.5,239.6,30.8,470,36,297.3,6.7,367.5-36.2,642-28a2511.41,2511.41,0,0,1,420,48"></path>
                        </g>
                        <g class="b">
                            <path class="d" d="M-127,404H1963V44c-140.1-28-343.3-46.7-566,22-75.5,23.3-118.5,45.9-162,64-48.6,20.2-404.7,128-784,0C355.2,97.7,341.6,78.3,235,50,86.6,10.6-41.8,6.9-127,10"></path>
                        </g>
                        <g class="b">
                            <path class="d" d="M1979,462-155,446V106C251.8,20.2,576.6,15.9,805,30c167.4,10.3,322.3,32.9,680,56,207,13.4,378,20.3,494,24"></path>
                        </g>
                        <g class="b">
                            <path class="d" d="M1998,484H-243V100c445.8,26.8,794.2-4.1,1035-39,141-20.4,231.1-40.1,378-45,349.6-11.6,636.7,73.8,828,150"></path>
                        </g>
                    </svg>
                </div>
            </section>
        </main>
    </div>
    <div id="layoutDefault_footer">
        <footer class="footer pt-5 pb-5 mt-auto bg-black footer-dark">
            <div class="container">
                <h5 class="text-white">music you'll (probably) like</h5>
                <p class="mb-2">An open source project created by <a href="https://alexgokhale.com">Alex Gokhale</a>.</p>
                <div class="icon-list-social">
                    <a class="icon-list-social-link" href="https://gitlab.com/alex.gokhale/spotify-suggestions" target="_blank">
                        <i class="fab fa-gitlab" title="Source Code"></i>
                    </a>
                    <a class="icon-list-social-link" href="https://twitter.com/AlexG_MCR" target="_blank">
                        <i class="fab fa-twitter" title="Twitter"></i>
                    </a>
                    <a class="icon-list-social-link" href="https://alexgokhale.com" target="_blank">
                        <i class="fas fa-globe" title="Portfolio"></i>
                    </a>
                </div>
            </div>
        </footer>
    </div>
</div>
<script>
    AOS.init({
        disable: 'mobile',
        duration: 600,
        once: true
    });
    
    feather.replace();
</script>
<script src="~/js/index.js"></script>
<audio id="song"></audio>

<input type="hidden" id="bugsnag-apikey" value="@ViewData["bugsnag-apikey"]">
<input type="hidden" id="app-version" value="@ViewData["app-version"]">